Calculus/urls.py
from django.urls import path
from Calculus.views import IndexView, Task1View, Result1View, Task2View, Result2View, InfoTask1View, AboutTeamView, ProjectTargetsView

app_name = 'Calculus'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('task1/', Task1View.as_view(), name='task1'),
    path('result1/<int:task_id>/', Result1View.as_view(), name='result1'),
    path('task2/', Task2View.as_view(), name='task2'),
    path('result2/<int:task_id>/', Result2View.as_view(), name='result2'),
    path('info-task1/', InfoTask1View.as_view(), name='info-task'),
    path('about_team/', AboutTeamView.as_view(), name='about-team'),
    path('targets/', ProjectTargetsView.as_view(), name='targets')
]

Psy_Chem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

static_urlpatterns = [
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    re_path(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Calculus.urls', namespace='main')),
    path("", include(static_urlpatterns)),
]

templates/base.html
{%  load static %}


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% block style %} {% endblock %}
    <link type="image/x-icon" href="{% static '/img/misis.png' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static '/img/misis.png' %}" rel="icon">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">
          <img src='{% static "/img/misis.png" %}' alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
          МИСИС<sub>бжд</sub>
          </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <a class="navbar-brand" href="#">
              <img src='{% static "/img/misis.png" %}' alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
              МИСИС<sub>бжд</sub>
              </a>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Задачи
                  </a>
                  <ul class="dropdown-menu" style="font-size: 0.9em;">
                    <li><a class="dropdown-item" href="{% url 'main:task1' %}">Проектировка защитного заземление</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:task2' %}">Подборка площади сечения нулевого провода</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'main:info-task' %}">Справочные материалы</a>
                </li>
               <li>
                  <hr>
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  О проекте
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'main:about-team' %}">Команда</a></li>
                  <li><a class="dropdown-item" href="{% url 'main:targets' %}">О проекте</a></li>
                </ul>
              </li>
              <li>
                <hr>
              </li>
              <li>
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Админ панель</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    {% block breadcrumb %} {% endblock %}
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>